# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: xxxxx
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
